name: Build
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      PACKAGE: ghcr.io/${{github.repository_owner}}/clang-format
    steps:
      - name: Gather info
        id: info
        run: |
          TAG="${PACKAGE}:latest"
          echo "::set-output name=tag::${TAG,,}"
      - name: Set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: image=moby/buildkit:master
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Build image
        if: github.ref != 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          builder: ${{steps.buildx.outputs.name}}
          context: .
          tags: ${{steps.info.outputs.tag}}
          push: false
      - name: Login into registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1.6.0
        with:
          registry: ghcr.io
          username: ${{secrets.CONTAINER_REGISTRY_USER}}
          password: ${{secrets.CONTAINER_REGISTRY_TOKEN}}
      - name: Build & push image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          builder: ${{steps.buildx.outputs.name}}
          context: .
          tags: ${{steps.info.outputs.tag}}
          push: true
