name: Build
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Gather info
        id: info
        run: |
          PACKAGE='ghcr.io/${{github.repository_owner}}/clang-format'
          TAGS="${PACKAGE}:latest"
          echo "##[set-output name=package;]${PACKAGE,,}"
          echo "##[set-output name=tags;]${TAGS,,}"
      - name: Set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: image=moby/buildkit:master
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Build image
        if: github.ref != 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          builder: ${{steps.buildx.outputs.name}}
          context: .
          tags: ${{steps.info.outputs.tags}}
          push: false
          load: true
      - name: Run tests
        run: docker run ${{steps.info.outputs.package}} clang-format --version
      - name: Login into registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1.7.0
        with:
          registry: ghcr.io
          username: ${{secrets.CONTAINER_REGISTRY_USER}}
          password: ${{secrets.CONTAINER_REGISTRY_TOKEN}}
      - name: Build & push image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          builder: ${{steps.buildx.outputs.name}}
          context: .
          tags: ${{steps.info.outputs.tags}}
          push: true
